
#db source url
#spring.datasource.url=jdbc:mysql://localhost:3306/study?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study1?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&useSSL=false
  #db response name
    username: study
  #db response password
    password: P@ssw0rd
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
   show-sql: true
   generate-ddl: true
   open-in-view: false
   hibernate:
    ddl-auto: update
   properties:
    org.hibernate.envers.audit_table_suffix: _revision
    hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    dialect.storage_engine: innodb
    format_sql: true